kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-reader
rules:
{{ if .Values.backupSecrets }}
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
{{ end }}
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - rolebindings
  verbs:
  - get
  - watch
  - list
