apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name | quote }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.name | quote }}
          servicePort: {{ .Values.port }}
