apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name | quote }}
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.name | quote }}
  sessionAffinity: None
  type: ClusterIP
